SecAction "id:900000,phase:1,pass,nolog,tag:'OWASP_CRS',ver:'OWASP_CRS/4.25.0',setvar:tx.blocking_paranoia_level=1"
SecAction "id:900001,phase:1,pass,nolog,tag:'OWASP_CRS',ver:'OWASP_CRS/4.25.0',setvar:tx.detection_paranoia_level=1"
