services:
  juice-shop:
    image: bkimminich/juice-shop:latest
    container_name: juice-shop
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - waf-soc

  waf:
      image: owasp/modsecurity-crs:nginx
      container_name: waf-proxy
      restart: unless-stopped
      depends_on:
        - juice-shop
      ports:
        - "80:8080"
      environment:
        PORT: 8080
        BACKEND: http://juice-shop:3000
        SERVERNAME: localhost
        ERRORLOG: /var/log/modsecurity/error.log
        ACCESSLOG: /var/log/nginx/access.log
        MODSEC_AUDIT_LOG: /var/log/modsecurity/audit.log
        MODSEC_AUDIT_LOG_FORMAT: JSON
        MODSEC_AUDIT_LOG_TYPE: Serial
        MODSEC_AUDIT_ENGINE: RelevantOnly
        MODSEC_RULE_ENGINE: "On"
        BLOCKING_PARANOIA: 2
        DETECTION_PARANOIA: 2
      volumes:
        - ./logs/modsecurity:/var/log/modsecurity
        - ./logs/nginx:/var/log/nginx
        - ./modsecurity-exclusions.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:ro
        - ./nginx-templates/default.conf.template:/etc/nginx/templates/conf.d/default.conf.template:ro
      networks:
        - waf-soc

  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki-data:/loki
    networks:
      - waf-soc

  promtail:
    image: grafana/promtail:2.9.8
    container_name: promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
      - waf
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      - ./logs/modsecurity:/var/log/modsecurity:ro
      - ./logs/nginx:/var/log/nginx:ro
      - promtail-positions:/var/lib/promtail
    networks:
      - waf-soc

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - loki
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana-data:/var/lib/grafana
    networks:
      - waf-soc

networks:
  waf-soc:
    driver: bridge

volumes:
  loki-data:
  promtail-positions:
  grafana-data: